AlyMoly/mantenedor/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^subcategorias/(?P<supercategoria_id>\d*)/$',
            views.subcategorias,
            name='subcategorias'),
    url(r'^subcategoria_de_producto/(?P<producto_id>\d*)/$',
        views.subcategoria_de_producto,
        name='subcategoria_de_producto'),
    url(r'^info_producto/(?P<producto_id>\d*)/$',
        views.info_producto,
        name='info_producto')
]

AlyMoly/urls.py
#-*- encoding: UTF-8 -*-
from django.conf.urls import url, include
from settings import MEDIA_ROOT, DEBUG
from django.views.generic import RedirectView
from django.contrib import admin
from django.views.static import serve
admin.autodiscover()

handler500 = 'django.views.defaults.server_error'
handler404 = 'django.views.defaults.page_not_found'

urlpatterns = [
    url(r'^admin_tools/', include('admin_tools.urls')),
    url('^$', RedirectView.as_view(url='/venta/')),
    url(r'^admin/', include('AlyMoly.mantenedor.urls')),
    url(r'^admin/', include('AlyMoly.movimiento.urls')),
    url(r'^admin/reporte/', include('AlyMoly.reporte.urls', namespace='reporte')),
    url(r'^admin/inventario/', include('AlyMoly.inventario.urls', namespace='inventario')),
    url(r'^admin/utils/', include('AlyMoly.utils.urls', namespace='utils')),
    url(r'^venta/', include('AlyMoly.venta.urls', namespace='venta')),
    url(r'^devolucion/', include('AlyMoly.devolucion.urls')),
    url(r'^admin/', include(admin.site.urls)),
]

if DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {
            'document_root': MEDIA_ROOT,
        }),
    ]

AlyMoly/movimiento/models.py
#-*- encoding: UTF-8 -*-
###############################################
# Todos los derechos reservados a:            #
# CreceLibre Consultores en Tecnologías Ltda. #
#                                             #
# ©Milton Inostroza Aguilera                  #
# minostro@minostro.com                       #
# 2009                                        #
###############################################
from django.db import models
from AlyMoly.mantenedor.models import Proveedor, Producto, Bodega
from django.db.models.signals import post_save, pre_save
from AlyMoly.movimiento.signal import ingreso_mercaderia, egreso_mercaderia, traspaso_mercaderia, actualizar_costo
from AlyMoly.tags.templatetags.tags import milesformat

class ProductoBodega(models.Model):
    """
    Representa las existencias de productos en una bodega
    """
    producto = models.ForeignKey(Producto)
    bodega = models.ForeignKey(Bodega)
    existencia = models.PositiveIntegerField()

    def __unicode__(self):
        return u'%s'%(self.producto.nombre + ' ' + self.bodega.ubicacion)

    def save(self, force_insert=False, force_update=False):
        """
            utilizado solamente para sqlite3, ya que no soporta unsigned integer.
            En la interfaz admin no hay problema ya que django provee verificación
            para el tipo de campo que es existencia, pero el problema está cuando
            se utiliza este campo en el proceso de venta.
        """
        if self.existencia < 0 and not len(ProductoBodega.objects.filter(producto=self.producto)) == 0:
            producto_bodega_ = ProductoBodega.objects.get(producto=self.producto,bodega=self.bodega)
            raise Exception(u"Para: %s existen solamente %s unidades"%(self.producto.nombre, producto_bodega_.existencia))
        super(ProductoBodega, self).save()

    class Meta:
        unique_together = ('producto','bodega')

class Traspaso(models.Model):
    """
    Representa los movimientos de traspaso entre bodegas
    """
    origen = models.ForeignKey(Bodega, related_name="origen", help_text=u'Seleccione la bodega de origen')
    destino = models.ForeignKey(Bodega, related_name="destino",help_text=u'Seleccione la bodega de destino')
    producto = models.ForeignKey(Producto)
    cantidad = models.PositiveIntegerField(help_text=u'Ingrese la cantidad de traspaso.')
    fecha_traspaso = models.DateField(
                               u'Fecha de Traspaso',
                               auto_now_add=True)

    def __unicode__(self):
        return u'Traspaso #%s' % self.id

    class Meta:
        verbose_name = u"Traspaso de mercadería"
        verbose_name_plural = u"Traspasos de mercaderías"

class Ingreso(models.Model):
    """
    Representa un ingreso de mercadería
    """
    existencia = models.ForeignKey(ProductoBodega)
    proveedor = models.ForeignKey(Proveedor, help_text=u"Seleccione el proveedor de ingreso de mercadería.")
    fecha_ingreso = models.DateField(
                               u'Fecha de Ingreso',
                               auto_now_add=True)
    cantidad = models.PositiveIntegerField(u"Stock de ingreso",
                                        help_text=u"Ingrese el stock \
                                        que se está recibiendo.")
    precio_costo = models.PositiveIntegerField(
                                   u"Precio costo de unidad ($), incluído I.V.A.",
                                   help_text=u"Ingrese el precio unitario de la mercadería.   ")

    def sucursal(self):
        return self.existencia.bodega.sucursal
    sucursal.short_description = u'sucursal'
    def bodega(self):
        return self.existencia.bodega.ubicacion
    bodega.short_description = u'bodega'
    def producto(self):
        return self.existencia.producto
    producto.short_description = u'producto'
    def costo(self):
        return milesformat(unicode(self.precio_costo))
    costo.short_description = u'costo CLP($)'
    def codigo_barra(self):
        return self.existencia.producto.codigo_barra
    codigo_barra.short_description = u'código de barra'

    def __unicode__(self):
        return u'%s' % self.existencia.producto.__unicode__()

    class Meta:
        verbose_name = u"Ingreso de mercadería"
        verbose_name_plural = u"Ingresos de mercaderías"

class Egreso(models.Model):
    """
    Representa un egreso de mercadería
    """
    existencia = models.ForeignKey(ProductoBodega)
    fecha_egreso = models.DateField(
                               u'Fecha de Egreso',
                               auto_now_add=True)
    cantidad = models.PositiveIntegerField(u"Cantidad de egreso",
                                        help_text=u"Ingrese la cantidad \
                                        que está egresando.")
    observacion = models.TextField(
                                   u"Obervación",
                                   help_text=u"Ingrese una observación de egreso.",
                                   null=True,blank=True)

    def sucursal(self):
        return self.existencia.bodega.sucursal
    sucursal.short_description = u'sucursal'
    def bodega(self):
        return self.existencia.bodega.ubicacion
    bodega.short_description = u'bodega'
    def producto(self):
        return self.existencia.producto
    producto.short_description = u'producto'
    def codigo_barra(self):
        return self.existencia.producto.codigo_barra
    codigo_barra.short_description = u'código de barra'

    def __unicode__(self):
        return u'%s' % self.existencia.producto.__unicode__()

    class Meta:
        verbose_name = u"Egreso de mercadería"
        verbose_name_plural = u"Egresos de mercaderías"

pre_save.connect(traspaso_mercaderia, Traspaso)
pre_save.connect(ingreso_mercaderia,Ingreso)
pre_save.connect(egreso_mercaderia,Egreso)
post_save.connect(actualizar_costo, Ingreso)

AlyMoly/reporte/forms.py
#-*- encoding: UTF-8 -*-
from django import forms
from AlyMoly.mantenedor.models import Proveedor, Categoria, Bodega
from AlyMoly.reporte.clases import Reporte
from django.forms.utils import ErrorList
import datetime

class ReporteForm(forms.Form):
    'Formulario que define el campo formato de un reporte'
    formato = forms.ChoiceField(
                               required=True,
                               label=u"Formato",
                               widget=forms.Select(attrs={'style':'width:230px'}),
                               help_text=u"Seleccione el formato"
                               )
    def __init__(self, *args, **kwargs):
        super(ReporteForm, self).__init__(*args, **kwargs)
        self.fields['formato'].choices = [(x,x.upper()) for x in Reporte.FORMATO]

class ExistenciaPorCategoriaForm(ReporteForm):
    'Formulario de generación de reporte de Existencia por categoría'

    bodega = forms.ModelChoiceField(
                               required=True,
                               label=u"Bodega",
                               queryset=Bodega.objects.all(),
                               widget=forms.Select(attrs={'style':'width:230px'}),
                               help_text=u"Seleccione la Bodega"
                               )

    categoria = forms.ChoiceField(
                               required=True,
                               widget=forms.Select(attrs={'style':'width:230px'}),
                               label=u"Categoría",
                               help_text=u"Seleccione la categoría",
                               )

    TODAS = 1
    BASE_OPT = (TODAS,'TODAS')
    def __init__(self, *args, **kwargs):
        super(ExistenciaPorCategoriaForm, self).__init__(*args, **kwargs)
        self.fields['categoria'].choices = [ExistenciaPorCategoriaForm.BASE_OPT] + \
                                map(lambda x: (x.id,x.nombre.title()),
                                Categoria.objects.all())

    def clean_bodega(self):
        bodega = self.cleaned_data["bodega"]
        return bodega.id

class TipoVentaForm(ReporteForm):
    'Formulario que define el tipo de venta: exenta, no exenta, todas'
    TODOS = 1
    EXENTOS = 2
    AFECTOS = 3
    OPCION_VENTA = (
                     (TODOS,'TODOS'),
                     (EXENTOS,'EXENTOS'),
                     (AFECTOS,'AFECTOS'),
                     )
    tipo = forms.ChoiceField(
                               required=True,
                               label=u"Tipo",
                               widget=forms.Select(attrs={'style':'width:230px'}),
                               help_text=u"Seleccione el tipo de reporte de ventas",
                               choices = OPCION_VENTA
                               )

class ProductoForm(ReporteForm):
    'Formulario de generacion de reporte de Productos'
    TODOS = 1
    CODIGO_BARRA = 2
    CODIGO_MANUAL = 3
    EXENTOS = 4
    AFECTOS = 5
    PROMOCIONES = 6
    OPCION_PRODUCTO = (
                     (TODOS,'TODOS'),
                     (CODIGO_BARRA,'SOLO CODIGO DE BARRA'),
                     (CODIGO_MANUAL,'SOLO CODIGO MANUAL'),
                     (EXENTOS,'SOLO EXENTOS'),
                     (AFECTOS,'SOLO AFECTOS'),
                     (PROMOCIONES,'SOLO PROMOCIONES'),
                     )

    tipo_producto = forms.ChoiceField(
                               required=True,
                               label=u"Tipo",
                               widget=forms.Select(attrs={'style':'width:230px'}),
                               help_text=u"Seleccione el tipo de reporte de producto",
                               choices = OPCION_PRODUCTO
                               )

class VentasForm(TipoVentaForm):
    'Formulario de generaciñon de reporte de por rango de fecha'
    fecha_inicio = forms.DateField(input_formats = ['%d/%m/%Y'],
                                   widget=forms.TextInput({'class':'tipo_fecha'}),
                                   help_text=u'Seleccione el período de inicio')
    fecha_fin = forms.DateField(label=u'Fecha término',input_formats = ['%d/%m/%Y'],
                                   widget=forms.TextInput({'class':'tipo_fecha'}),
                                help_text=u'Seleccione el período de término')
    def __init__(self, *args, **kwargs):
        super(VentasForm, self).__init__(*args, **kwargs)
        self.fields['fecha_inicio'].initial = datetime.date.today().strftime('%d/%m/%Y')
        self.fields['fecha_fin'].initial = datetime.date.today().strftime('%d/%m/%Y')

    class Media:
        js = ('/media/js/jquery.js',
              '/media/js/jquery-ui-datepicker.min.js',
              '/media/js/ventas/seleccion_fecha.js',
              )
        css = {'all':('/media/css/jquery-datepicker.css',)}

    def clean(self):
        """ Método de validación personalizado que válida si
        la fecha de inici sea menor que la fecha de término """
        cleaned_data = self.cleaned_data

        fecha_inicio = cleaned_data.get("fecha_inicio")
        fecha_fin = cleaned_data.get("fecha_fin")


        if fecha_inicio > fecha_fin:
            # Se ingresa la información de error.
            msg = u"La fecha de inicio debe ser menor que la fecha de término."
            self._errors["fecha_fin"] = ErrorList([msg])

            # Como estos campos ya no son válidos, entonces
            # se eliminan del diccionario de objetos válidos
            del cleaned_data["fecha_inicio"]
            del cleaned_data["fecha_fin"]

        # Se retorna el diccioario de datos limpios
        return cleaned_data

class VentasDiariasForm(TipoVentaForm):
    'Formulario de generación de reporte de ventas diarias'
    fecha = forms.DateField(input_formats = ['%d/%m/%Y'],
                                   widget=forms.TextInput({'class':'tipo_fecha'}),
                                   help_text=u'Seleccione la fecha de venta')
    def __init__(self, *args, **kwargs):
        super(VentasDiariasForm, self).__init__(*args, **kwargs)
        self.fields['fecha'].initial = datetime.date.today().strftime('%d/%m/%Y')

    class Media:
        js = ('/media/js/jquery.js',
              '/media/js/jquery-ui-datepicker.min.js',
              '/media/static/js/seleccion_fecha.js',
              )
        css = {'all':('/media/css/jquery-datepicker.css',)}

class VentasPorTurnoForm(VentasForm):
    'Formulario de generación reporte de ventas por turno'
    """
    sucursal = forms.ModelChoiceField(
                               queryset=Sucursal.objects.all(),
                               required=True,
                               widget=forms.Select(attrs={'style':'width:230px'}),
                               label=u"Sucursal",
                               help_text=u"Seleccione la sucursal",
                               )
    """
    def __init__(self, *args, **kwargs):
        super(VentasPorTurnoForm, self).__init__(*args, **kwargs)
        self.fields['tipo'].initial = 1
        self.fields['formato'].required = False

    class Media:
        js = ('/media/js/jquery.js',
              '/media/js/forms/ventas_por_turno.js',
              )

class BuscarTurnoForm(forms.Form):
    """Busca un registro de turno dentro de una tabla"""
    class Media:
        #Se carga la magia necesaria para recargar las subcategorías vía ajax
        js = (
            '/media/js/jquery.quicksearch.pack.js',
            '/media/js/forms/buscar_turno.js',
        )


class VentaMesForm(ReporteForm):
    'Formulario de generacion de reporte de Productos'
    OPCION_MES = (
                     (1,'Enero'),
                     (2,'Febrero'),
                     (3,'Marzo'),
                     (4,'Abril'),
                     (5,'Mayo'),
                     (6,'Junio'),
                     (7,'Julio'),
                     (8,'Agosto'),
                     (9,'Septiembre'),
                     (10,'Octubre'),
                     (11,'Noviembre'),
                     (12,'Diciembre'),
                     )

    REPORTE_DETALLE = 1
    REPORTE_RESUMIDO = 2

    OPCION_REPORTE = (
                      (REPORTE_DETALLE,'Detalle'),
                      (REPORTE_RESUMIDO,'Resumen'),
                      )

    def __init__(self, anios, dia, *args, **kwargs):
        super(VentaMesForm,self).__init__(*args,**kwargs)
        inicio = anios['inicio'].year
        fin = anios['fin'].year
        if inicio == fin:
            fin = inicio
        self.fields['anio'].choices = [(x,x) for x in tuple(range(inicio,fin+1))]
        self.fields['mes'].initial = dia.month
        self.fields['anio'].initial = dia.year

    tipo_reporte = forms.ChoiceField(
                               label=u"Tipo",
                               widget=forms.Select(attrs={'style':'width:230px'}),
                               help_text=u"Seleccione el tipo de reporte que desea visualizar",
                               choices = OPCION_REPORTE,
                               )

    mes = forms.ChoiceField(
                               label=u"Mes",
                               widget=forms.Select(attrs={'style':'width:230px'}),
                               help_text=u"Seleccione el mes",
                               choices = OPCION_MES,
                               )
    anio = forms.ChoiceField(
                               label=u"Año",
                               widget=forms.Select(attrs={'style':'width:230px'}),
                               help_text=u"Seleccione el año",
                               )

class VentasGraficosForm(ReporteForm):
    'Formulario de generaciñon de reporte de por rango de fecha'

    OPCION_ELEMENTO = (
                     (1,'Productos'),
                     (2,'Promociones'),
                     )

    fecha_inicio = forms.DateField(input_formats = ['%d/%m/%Y'],
                                   widget=forms.TextInput({'class':'tipo_fecha'}),

AlyMoly/mantenedor/templates/mantenedor/producto_compuesto/change.html
{% extends "admin/base_site.html" %}
{% load i18n admin_modify adminmedia %}

{% block extrahead %}{{ block.super }}
{{ form.media }}
{% endblock %}

{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{% admin_media_prefix %}css/forms.css" />{% endblock %}

{% block coltype %}{% if ordered_objects %}colMS{% else %}colM{% endif %}{% endblock %}

{% block bodyclass %}{{ opts.app_label }}-{{ opts.object_name.lower }} change-form{% endblock %}
{% block breadcrumbs %}{% if not is_popup %}
<div class="breadcrumbs">
    <a href="/admin">{% trans "Home" %}</a>
    &rsaquo; <a href="/admin/mantenedor/">Mantenedor</a>
    &rsaquo; <a href="/admin/producto_compuesto/">Producto Compuesto</a>
    &rsaquo; Nuevo Producto Compuesto
</div>
{% endif %}{% endblock %}
{% block content %}<h2>Producto Compuesto</h2>
<div id="content-main">
    {% block object-tools %}
    {% if change %}{% if not is_popup %}
    <ul class="object-tools">
        <li>
            <a href="history/" class="historylink">{% trans "History" %}</a>
        </li>
        {% if has_absolute_url %}
        <li>
            <a href="../../../r/{{ content_type_id }}/{{ object_id }}/" class="viewsitelink">{% trans "View on site" %}</a>
        </li>{% endif%}
    </ul>
    {% endif %}{% endif %}
    {% endblock %}
    <form action="." method="POST">
        <div>
            <fieldset class="module aligned extrapretty">
                <h2>Producto Compuesto</h2>
                <div class="description">
                    En el siguiente formulario se relacionan los productos como <strong>productos compuestos</strong>
                    de otros productos. 
                    <br/>
                    <br/>
                </div>
                <div class="form-row nombre marca  ">
                    <div class="field-box">
                        {{ form.codigo_barra_compuesto.errors }}
                        <label class="required" for="id_sucursal">
                            {{ form.codigo_barra_compuesto.label }}:
                        </label><span class="nombre_producto" style="font-size:2em"></span>
                        {{ form.codigo_barra_compuesto }}
                        <p class="help">
                            {{ form.codigo_barra_compuesto.help_text }}
                        </p>
                    </div>
                </div>
                <div class="form-row nombre marca  ">
                    <div class="field-box">
                        {{ form.codigo_barra_compone.errors }}
                        <label class="required inline" for="id_proveedor">
                            {{ form.codigo_barra_compone.label }}:
                        </label><span class="nombre_producto" style="font-size:2em"></span>
                        {{ form.codigo_barra_compone }}
                        <p class="help">
                            {{ form.codigo_barra_compone.help_text }}
                        </p>
                    </div>
                </div>
                <div class="form-row nombre marca  ">
                    <div class="field-box">
                        {{ form.cantidad_compone.errors }}
                        <label class="required inline" for="id_proveedor">
                            {{ form.cantidad_compone.label }}:
                        </label>
                        {{ form.cantidad_compone }}
                        <p class="help">
                            {{ form.cantidad_compone.help_text }}
                        </p>
                    </div>
                </div>
            </fieldset>
            <div class="submit-row">
                {% if show_delete_link %}
                <p class="deletelink-box">
                    <a href="delete/" onclick="return confirm('A continuaci&oacute;n se eliminar&aacute; la relaci&oacute;n de producto compuesto. &#191;Desea continuar?')" class="deletelink">{% trans "Delete" %}</a>
                </p>{% endif %}<input type="submit" name="_save" class="default" value="Grabar"/>
            </div>
        </div>
    </form>
    <div id="inventario_actual">
    </div>
</div>{% endblock %}

AlyMoly/mantenedor/templates/mantenedor/producto_compuesto/change_list.html
{% extends "admin/base_site.html" %}
{% load adminmedia admin_list i18n %}

{% block extrastyle %}
  {{ block.super }}
  <link rel="stylesheet" type="text/css" href="{% admin_media_prefix %}css/changelists.css" />
  {% if cl.formset %}
    <link rel="stylesheet" type="text/css" href="{% admin_media_prefix %}css/forms.css" />
    <script type="text/javascript" src="../../jsi18n/"></script>
  {% endif %}
  {{ media }}
  {% if not actions_on_top and not actions_on_bottom %}
    <style>
      #changelist table thead th:first-child {width: inherit}
    </style>
  {% endif %}
{% endblock %}

{% if not is_popup %}{% block breadcrumbs %}
<div class="breadcrumbs">
    <a href="/admin">{% trans "Home" %}</a>
    &rsaquo; <a href="/admin/mantenedor/">Mantenedor</a>
    &rsaquo; Producto Compuesto
</div>{% endblock %}{% endif %}
{% block coltype %}flex{% endblock %}
{% block content %}
<h1>Escoja el producto compuesto a modificar</h1>
<div id="content-main">

    <ul class="object-tools">
        <li>
            <a href="add/" class="addlink">A&#241;adir Producto Compuesto</a>
        </li>
    </ul>
	<div id="changelist" class="module">
    {% if results %}
    <table cellspacing="0">
        <thead>
            <tr class="{% cycle 'row1' 'row2' %}">
                <th>
                    <a href="#">C&oacute;digo de barra</a>
                </th>
                <th>
                    <a href="#">Nombre</a>
                </th>
                <th>
                    <a href="#">Marca</a>
                </th>
                <th>
                    <a href="#">Categor&iacute;a</a>
                </th>
                <th>
                    <a href="#">Tipo de envase</a>
                </th>
                <th>
                    <a href="#">Cantidad</a>
                </th>
                <th>
                    <a href="#">Capacidad</a>
                </th>
            </tr>
        </thead>
        <tbody>
            {% for result in results %}
            <tr class="{% cycle 'row1' 'row2' %}">
                <th>
                    <a href="{{result.id}}">{{ result.compone.codigo_barra }}</a>
                </th>
                <td>
                    {{ result.compone.nombre }}
                </td>
                <td>
                    {{ result.compone.marca }}
                </td>
                <td>
                    {{ result.compone.categoria }}
                </td>
                <td>
                    {{ result.compone.tipo_envase }}
                </td>
                <td>
                    {{ result.cantidad_compone }}
                </td>
                <td>
                    {{ result.capacidad }}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
	</div>
    {% endif %}
</div>
</div>
{% endblock %}