AlyMoly/reporte/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from . import views

urlpatterns = [
    url(r'^productos/$',
        views.productos,
        name='productos'),
    url(r'^existencias/$',
        views.existencias,
        name='existencias'),
    url(r'^ventas/$',
        views.ventas,
        name='ventas'),
    url(r'^ventas/(?P<turno_id>\d*)/(?P<formato>pdf|html)/(?P<resumen>todos|afectos|exentos|promociones|devoluciones)/$',
        views.generar_ventas,
        name='generar_ventas'),
    url(r'^ventas/mes/$',
        views.ventas_mes,
        name='ventas_mes'),
    url(r'^ventas/grafico/categoria/$',
        views.ventas_graficos_periodo_categoria,
        name='ventas_graficos_periodo_categoria'),
    url('^$', TemplateView.as_view(template_name='reporte/index.html'), name="index"),
    url('^img/get', views.get_birt_img,
        name='get_birt_img'),
]

AlyMoly/urls.py
#-*- encoding: UTF-8 -*-
from django.conf.urls import url, include
from settings import MEDIA_ROOT, DEBUG
from django.views.generic import RedirectView
from django.contrib import admin
from django.views.static import serve
admin.autodiscover()

handler500 = 'django.views.defaults.server_error'
handler404 = 'django.views.defaults.page_not_found'

urlpatterns = [
    url(r'^admin_tools/', include('admin_tools.urls')),
    url('^$', RedirectView.as_view(url='/venta/')),
    url(r'^admin/', include('AlyMoly.mantenedor.urls')),
    url(r'^admin/', include('AlyMoly.movimiento.urls')),
    url(r'^admin/reporte/', include('AlyMoly.reporte.urls', namespace='reporte')),
    url(r'^admin/inventario/', include('AlyMoly.inventario.urls', namespace='inventario')),
    url(r'^admin/utils/', include('AlyMoly.utils.urls', namespace='utils')),
    url(r'^venta/', include('AlyMoly.venta.urls', namespace='venta')),
    url(r'^devolucion/', include('AlyMoly.devolucion.urls')),
    url(r'^admin/', include(admin.site.urls)),
]

if DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {
            'document_root': MEDIA_ROOT,
        }),
    ]

AlyMoly/venta/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^venta/$',views.venta),
    url(r'^cuerpo_venta/$',views.cuerpo_venta),
    url('^turno/abrir/$', views.turno_abrir),
    url('^turno/cerrar/$', views.turno_cerrar),
    url(r'^$',views.autentificacion),
    url(r'^elemento/add/(?P<cantidad_>\d+)/$',views.agregar_elemento),
    url(r'^elemento/delete/(?P<codigo_barra_>\S+)/$',views.eliminar),
    url(r'^elemento/aumentar/(?P<codigo_barra_>\S+)/$',views.aumentar),
    url(r'^elemento/disminuir/(?P<codigo_barra_>\S+)/$',views.disminuir),
    url(r'^elemento/(?P<codigo_barra_>\S+)/$',views.buscar_elemento),
    url(r'^medio_pago/(?P<medio_>\d+)/$',views.medio_pago),
    url(r'^vuelto/(?P<cantidad_>\d+)/$',views.calcular_vuelto),
    url(r'^registrar/$',views.registrar_venta),
    url(r'^cabecera/$',views.cabecera),
    url(r'^turno/cerrado/(?P<a_id>\d+)/$', views.turno_cerrado),
    url(r'^boleta/deposito/(?P<a_id>\d+)/$',views.boleta_deposito, name="ver_boleta")
]

AlyMoly/venta/models.py
#!/usr/bin/env python
#-*- encoding: UTF-8 -*-

###############################################
# Todos los derechos reservados a:            #
# CreceLibre Consultores en Tecnologías Ltda. #
#                                             #
# ©Milton Inostroza Aguilera                  #
# minostro@minostro.com                       #
# 2009                                        #
###############################################
from django.db import models
from AlyMoly.mantenedor.models import Producto, Promocion, Trabajador


class Turno(models.Model):
    """
        estado:
            1 --> abierto
            2 --> cerrado
    """
    fecha_apertura_sistema = models.DateTimeField()
    fecha_cierre_sistema = models.DateTimeField(null=True, blank=True)
    estado = models.IntegerField(default=1, blank=True)
    trabajador = models.ForeignKey(Trabajador, blank=True)
    monto_apertura_caja = models.IntegerField(default=0)
    monto_cierre_calculado = models.IntegerField(default=0, blank=True)
    monto_afecto = models.IntegerField(default=0, blank=True)
    monto_exento = models.IntegerField(default=0, blank=True)

    def monto_cierre_informado(self):
        return self.boletadeposito.total

    def estado_turno(self):
        if self.estado == 1:
            return "Abierto"
        else:
            return "Cerrado"

    def save(self, force_insert=False, force_update=False):
        """
            Al guardar un turno abierto se verifica que el trabajador ya no cuente con un
            turno abierto anteriormente.
        """
        if self.estado == 1 and len(Turno.objects.exclude(id=self.id).filter(trabajador__id=self.trabajador.id).filter(estado=1)) > 0:
            raise Exception(u"Usted ya cuenta con un turno abierto.")
        super(Turno, self).save(force_insert, force_update)


class BoletaDeposito(models.Model):
    turno = models.OneToOneField(Turno, blank=True)
    veintemil = models.PositiveIntegerField(default=0, blank=True)
    diezmil = models.PositiveIntegerField(default=0, blank=True)
    cincomil = models.PositiveIntegerField(default=0, blank=True)
    dosmil = models.PositiveIntegerField(default=0, blank=True)
    mil = models.PositiveIntegerField(default=0, blank=True)
    quinientos = models.PositiveIntegerField(default=0, blank=True)
    cien = models.PositiveIntegerField(default=0, blank=True)
    cincuenta = models.PositiveIntegerField(default=0, blank=True)
    diez = models.PositiveIntegerField(default=0, blank=True)
    tarjetas = models.PositiveIntegerField(default=0, blank=True)
    otros = models.PositiveIntegerField(default=0, blank=True)
    total = models.PositiveIntegerField(default=0, blank=True)


class Venta(models.Model):
    """
        medio_pago:
            1 --> efectivo
            2 --> otro
    """
    fecha_venta = models.DateTimeField()
    folio_boleta = models.PositiveIntegerField(null=True, blank=True)
    monto_total = models.PositiveIntegerField()
    monto_afecto = models.PositiveIntegerField()
    monto_exento = models.PositiveIntegerField()
    cantidad_productos = models.PositiveIntegerField()
    medio_pago = models.PositiveIntegerField()
    monto_pago = models.PositiveIntegerField(null=True)
    turno = models.ForeignKey('Turno')

    def __unicode__(self):
        return u"%s-%s" % (self.id, self.folio_boleta)


class LineaDetalle(models.Model):
    cantidad = models.IntegerField()
    precio_venta = models.IntegerField()
    precio_venta_total = models.IntegerField()
    producto = models.ForeignKey(Producto, null=True, blank=True)
    promocion = models.ForeignKey(Promocion, null=True, blank=True)
    venta = models.ForeignKey('Venta')

AlyMoly/reporte/forms.py
#-*- encoding: UTF-8 -*-
from django import forms
from AlyMoly.mantenedor.models import Proveedor, Categoria, Bodega
from AlyMoly.reporte.clases import Reporte
from django.forms.utils import ErrorList
import datetime

class ReporteForm(forms.Form):
    'Formulario que define el campo formato de un reporte'
    formato = forms.ChoiceField(
                               required=True,
                               label=u"Formato",
                               widget=forms.Select(attrs={'style':'width:230px'}),
                               help_text=u"Seleccione el formato"
                               )
    def __init__(self, *args, **kwargs):
        super(ReporteForm, self).__init__(*args, **kwargs)
        self.fields['formato'].choices = [(x,x.upper()) for x in Reporte.FORMATO]

class ExistenciaPorCategoriaForm(ReporteForm):
    'Formulario de generación de reporte de Existencia por categoría'

    bodega = forms.ModelChoiceField(
                               required=True,
                               label=u"Bodega",
                               queryset=Bodega.objects.all(),
                               widget=forms.Select(attrs={'style':'width:230px'}),
                               help_text=u"Seleccione la Bodega"
                               )

    categoria = forms.ChoiceField(
                               required=True,
                               widget=forms.Select(attrs={'style':'width:230px'}),
                               label=u"Categoría",
                               help_text=u"Seleccione la categoría",
                               )

    TODAS = 1
    BASE_OPT = (TODAS,'TODAS')
    def __init__(self, *args, **kwargs):
        super(ExistenciaPorCategoriaForm, self).__init__(*args, **kwargs)
        self.fields['categoria'].choices = [ExistenciaPorCategoriaForm.BASE_OPT] + \
                                map(lambda x: (x.id,x.nombre.title()),
                                Categoria.objects.all())

    def clean_bodega(self):
        bodega = self.cleaned_data["bodega"]
        return bodega.id

class TipoVentaForm(ReporteForm):
    'Formulario que define el tipo de venta: exenta, no exenta, todas'
    TODOS = 1
    EXENTOS = 2
    AFECTOS = 3
    OPCION_VENTA = (
                     (TODOS,'TODOS'),
                     (EXENTOS,'EXENTOS'),
                     (AFECTOS,'AFECTOS'),
                     )
    tipo = forms.ChoiceField(
                               required=True,
                               label=u"Tipo",
                               widget=forms.Select(attrs={'style':'width:230px'}),
                               help_text=u"Seleccione el tipo de reporte de ventas",
                               choices = OPCION_VENTA
                               )

class ProductoForm(ReporteForm):
    'Formulario de generacion de reporte de Productos'
    TODOS = 1
    CODIGO_BARRA = 2
    CODIGO_MANUAL = 3
    EXENTOS = 4
    AFECTOS = 5
    PROMOCIONES = 6
    OPCION_PRODUCTO = (
                     (TODOS,'TODOS'),
                     (CODIGO_BARRA,'SOLO CODIGO DE BARRA'),
                     (CODIGO_MANUAL,'SOLO CODIGO MANUAL'),
                     (EXENTOS,'SOLO EXENTOS'),
                     (AFECTOS,'SOLO AFECTOS'),
                     (PROMOCIONES,'SOLO PROMOCIONES'),
                     )

    tipo_producto = forms.ChoiceField(
                               required=True,
                               label=u"Tipo",
                               widget=forms.Select(attrs={'style':'width:230px'}),
                               help_text=u"Seleccione el tipo de reporte de producto",
                               choices = OPCION_PRODUCTO
                               )

class VentasForm(TipoVentaForm):
    'Formulario de generaciñon de reporte de por rango de fecha'
    fecha_inicio = forms.DateField(input_formats = ['%d/%m/%Y'],
                                   widget=forms.TextInput({'class':'tipo_fecha'}),
                                   help_text=u'Seleccione el período de inicio')
    fecha_fin = forms.DateField(label=u'Fecha término',input_formats = ['%d/%m/%Y'],
                                   widget=forms.TextInput({'class':'tipo_fecha'}),
                                help_text=u'Seleccione el período de término')
    def __init__(self, *args, **kwargs):
        super(VentasForm, self).__init__(*args, **kwargs)
        self.fields['fecha_inicio'].initial = datetime.date.today().strftime('%d/%m/%Y')
        self.fields['fecha_fin'].initial = datetime.date.today().strftime('%d/%m/%Y')

    class Media:
        js = ('/media/js/jquery.js',
              '/media/js/jquery-ui-datepicker.min.js',
              '/media/js/ventas/seleccion_fecha.js',
              )
        css = {'all':('/media/css/jquery-datepicker.css',)}

    def clean(self):
        """ Método de validación personalizado que válida si
        la fecha de inici sea menor que la fecha de término """
        cleaned_data = self.cleaned_data

        fecha_inicio = cleaned_data.get("fecha_inicio")
        fecha_fin = cleaned_data.get("fecha_fin")


        if fecha_inicio > fecha_fin:
            # Se ingresa la información de error.
            msg = u"La fecha de inicio debe ser menor que la fecha de término."
            self._errors["fecha_fin"] = ErrorList([msg])

            # Como estos campos ya no son válidos, entonces
            # se eliminan del diccionario de objetos válidos
            del cleaned_data["fecha_inicio"]
            del cleaned_data["fecha_fin"]

        # Se retorna el diccioario de datos limpios
        return cleaned_data

class VentasDiariasForm(TipoVentaForm):
    'Formulario de generación de reporte de ventas diarias'
    fecha = forms.DateField(input_formats = ['%d/%m/%Y'],
                                   widget=forms.TextInput({'class':'tipo_fecha'}),
                                   help_text=u'Seleccione la fecha de venta')
    def __init__(self, *args, **kwargs):
        super(VentasDiariasForm, self).__init__(*args, **kwargs)
        self.fields['fecha'].initial = datetime.date.today().strftime('%d/%m/%Y')

    class Media:
        js = ('/media/js/jquery.js',
              '/media/js/jquery-ui-datepicker.min.js',
              '/media/static/js/seleccion_fecha.js',
              )
        css = {'all':('/media/css/jquery-datepicker.css',)}

class VentasPorTurnoForm(VentasForm):
    'Formulario de generación reporte de ventas por turno'
    """
    sucursal = forms.ModelChoiceField(
                               queryset=Sucursal.objects.all(),
                               required=True,
                               widget=forms.Select(attrs={'style':'width:230px'}),
                               label=u"Sucursal",
                               help_text=u"Seleccione la sucursal",
                               )
    """
    def __init__(self, *args, **kwargs):
        super(VentasPorTurnoForm, self).__init__(*args, **kwargs)
        self.fields['tipo'].initial = 1
        self.fields['formato'].required = False

    class Media:
        js = ('/media/js/jquery.js',
              '/media/js/forms/ventas_por_turno.js',
              )

class BuscarTurnoForm(forms.Form):
    """Busca un registro de turno dentro de una tabla"""
    class Media:
        #Se carga la magia necesaria para recargar las subcategorías vía ajax
        js = (
            '/media/js/jquery.quicksearch.pack.js',
            '/media/js/forms/buscar_turno.js',
        )


class VentaMesForm(ReporteForm):
    'Formulario de generacion de reporte de Productos'
    OPCION_MES = (
                     (1,'Enero'),
                     (2,'Febrero'),
                     (3,'Marzo'),
                     (4,'Abril'),
                     (5,'Mayo'),
                     (6,'Junio'),
                     (7,'Julio'),
                     (8,'Agosto'),
                     (9,'Septiembre'),
                     (10,'Octubre'),
                     (11,'Noviembre'),
                     (12,'Diciembre'),
                     )

    REPORTE_DETALLE = 1
    REPORTE_RESUMIDO = 2

    OPCION_REPORTE = (
                      (REPORTE_DETALLE,'Detalle'),
                      (REPORTE_RESUMIDO,'Resumen'),
                      )

    def __init__(self, anios, dia, *args, **kwargs):
        super(VentaMesForm,self).__init__(*args,**kwargs)
        inicio = anios['inicio'].year
        fin = anios['fin'].year
        if inicio == fin:
            fin = inicio
        self.fields['anio'].choices = [(x,x) for x in tuple(range(inicio,fin+1))]
        self.fields['mes'].initial = dia.month
        self.fields['anio'].initial = dia.year

    tipo_reporte = forms.ChoiceField(
                               label=u"Tipo",
                               widget=forms.Select(attrs={'style':'width:230px'}),
                               help_text=u"Seleccione el tipo de reporte que desea visualizar",
                               choices = OPCION_REPORTE,
                               )

    mes = forms.ChoiceField(
                               label=u"Mes",
                               widget=forms.Select(attrs={'style':'width:230px'}),
                               help_text=u"Seleccione el mes",
                               choices = OPCION_MES,
                               )
    anio = forms.ChoiceField(
                               label=u"Año",
                               widget=forms.Select(attrs={'style':'width:230px'}),
                               help_text=u"Seleccione el año",
                               )

class VentasGraficosForm(ReporteForm):
    'Formulario de generaciñon de reporte de por rango de fecha'

    OPCION_ELEMENTO = (
                     (1,'Productos'),
                     (2,'Promociones'),
                     )

    fecha_inicio = forms.DateField(input_formats = ['%d/%m/%Y'],
                                   widget=forms.TextInput({'class':'tipo_fecha'}),

AlyMoly/reporte/templates/reporte/venta_grafico_periodo.html
{% extends "admin/base_site.html" %}
{% load i18n admin_modify adminmedia %}
{% block extrahead %}{{ block.super }}
{{ form.media }}
{% endblock %}
{% block extrastyle %}{{ block.super }}
<link rel="stylesheet" type="text/css" href="{% admin_media_prefix %}css/forms.css" />
{% endblock %}
{% block coltype %}{% if ordered_objects %}colMS{% else %}colM{% endif %}{% endblock %}
{% block bodyclass %}{{ opts.app_label }}-{{ opts.object_name.lower }} change-form{% endblock %}
{% block breadcrumbs %}{% if not is_popup %}
<div class="breadcrumbs">
    <a href="/admin">{% trans "Home" %}</a>
    &rsaquo; <a href="{% url reporte:index %}">Reporte</a>
    &rsaquo; <a href=".">Gr&aacute;fico de Ventas por per&iacute;odo</a>
</div>
{% endif %}{% endblock %}
{% block content %}<h2>Gr&aacute;fico de Ventas por per&iacute;odo</h2>
<div id="content-main">
    {% block object-tools %}
    {% if change %}{% if not is_popup %}
    <ul class="object-tools">
        <li>
            <a href="history/" class="historylink">{% trans "History" %}</a>
        </li>
        {% if has_absolute_url %}
        <li>
            <a href="../../../r/{{ content_type_id }}/{{ object_id }}/" class="viewsitelink">{% trans "View on site" %}</a>
        </li>{% endif%}
    </ul>
    {% endif %}{% endif %}
    {% endblock %}
    <form id="my_form" action="." method="POST" target='_blank'>
        <div>
            <fieldset class="module aligned extrapretty">
                <h2>Gr&aacute;fico de Ventas por per&iacute;odo</h2>
                <div class="description">
                    El siguiente formulario genera reportes de <strong>Gr&aacute;fico de Ventas por per&iacute;odo</strong>. 
                    <br/>
                    <br/>
                </div>
                <div class="form-row">
                    <div class="field-box">
                        {{ form.fecha_inicio.errors }}
                        <label class="required inline" for="id_mes">
                            {{ form.fecha_inicio.label }}:
                        </label>
                        {{ form.fecha_inicio }}
                        <p class="help">
                            {{ form.fecha_inicio.help_text }}
                        </p>
                    </div>
                    <div class="field-box">
                        {{ form.fecha_fin.errors }}
                        <label class="required inline" for="id_fecha_fin">
                            {{ form.fecha_fin.label }}:
                        </label>
                        {{ form.fecha_fin }}
                        <p class="help">
                            {{ form.fecha_fin.help_text }}
                        </p>
                    </div>
                </div>
                <div class="form-row">
                    <div class="field-box">
                        {{ form.elemento.errors }}
                        <label class="required inline" for="id_mes">
                            {{ form.elemento.label }}:
                        </label>
                        {{ form.elemento }}
                        <p class="help">
                            {{ form.elemento.help_text }}
                        </p>
                    </div>
                    <div class="field-box">
                        {{ form.formato.errors }}
                        <label class="required inline" for="id_formato">
                            {{ form.formato.label }}:
                        </label>
                        {{ form.formato }}
                        <p class="help">
                            {{ form.formato.help_text }}
                        </p>
                    </div>
                </div>				
            </fieldset>
            <div class="submit-row">
                <input type="submit" name="_save" class="default" value="Generar Informe"/>
            </div>
        </div>
    </form>
</div>{% endblock %}

AlyMoly/reporte/templates/reporte/venta_grafico_periodo_categoria.html
{% extends "admin/base_site.html" %}
{% load i18n admin_modify adminmedia %}
{% block extrahead %}{{ block.super }}
{{ form.media }}
{% endblock %}
{% block extrastyle %}{{ block.super }}
<link rel="stylesheet" type="text/css" href="{% admin_media_prefix %}css/forms.css" />
{% endblock %}
{% block coltype %}{% if ordered_objects %}colMS{% else %}colM{% endif %}{% endblock %}
{% block bodyclass %}{{ opts.app_label }}-{{ opts.object_name.lower }} change-form{% endblock %}
{% block breadcrumbs %}{% if not is_popup %}
<div class="breadcrumbs">
    <a href="/admin">{% trans "Home" %}</a>
    &rsaquo; <a href="{% url reporte:index %}">Reporte</a>
    &rsaquo; <a href=".">Gr&aacute;fico de Ventas por categor&iacute;a por per&iacute;odo</a>
</div>
{% endif %}{% endblock %}
{% block content %}<h2>Gr&aacute;fico de Ventas por categor&iacute;a por per&iacute;odo</h2>
<div id="content-main">
    {% block object-tools %}
    {% if change %}{% if not is_popup %}
    <ul class="object-tools">
        <li>
            <a href="history/" class="historylink">{% trans "History" %}</a>
        </li>
        {% if has_absolute_url %}
        <li>
            <a href="../../../r/{{ content_type_id }}/{{ object_id }}/" class="viewsitelink">{% trans "View on site" %}</a>
        </li>{% endif%}
    </ul>
    {% endif %}{% endif %}
    {% endblock %}
    <form id="my_form" action="." method="POST" target='_blank'>
        <div>
            <fieldset class="module aligned extrapretty">
                <h2>Gr&aacute;fico de Ventas por categor&iacute;a por per&iacute;odo</h2>
                <div class="description">
                    El siguiente formulario genera reportes de <strong>Gr&aacute;fico de Ventas por categor&iacute;a por per&iacute;odo</strong>. 
                    <br/>
                    <br/>
                </div>
                <div class="form-row">
                    <div class="field-box">
                        {{ form.fecha_inicio.errors }}
                        <label class="required inline" for="id_mes">
                            {{ form.fecha_inicio.label }}:
                        </label>
                        {{ form.fecha_inicio }}
                        <p class="help">
                            {{ form.fecha_inicio.help_text }}
                        </p>
                    </div>
                    <div class="field-box">
                        {{ form.fecha_fin.errors }}
                        <label class="required inline" for="id_fecha_fin">
                            {{ form.fecha_fin.label }}:
                        </label>
                        {{ form.fecha_fin }}
                        <p class="help">
                            {{ form.fecha_fin.help_text }}
                        </p>
                    </div>
                </div>
                <div class="form-row">
                    <div class="field-box">
                        {{ form.elemento.errors }}
                        <label class="required inline" for="id_mes">
                            {{ form.elemento.label }}:
                        </label>
                        {{ form.elemento }}
                        <p class="help">
                            {{ form.elemento.help_text }}
                        </p>
                    </div>
                    <div class="field-box">
                        {{ form.categoria.errors }}
                        <label class="required inline" for="id_categoria">
                            {{ form.categoria.label }}:
                        </label>
                        {{ form.categoria }}
                        <p class="help">
                            {{ form.categoria.help_text }}
                        </p>
                    </div>					
                    <div class="field-box">
                        {{ form.formato.errors }}
                        <label class="required inline" for="id_formato">
                            {{ form.formato.label }}:
                        </label>
                        {{ form.formato }}
                        <p class="help">
                            {{ form.formato.help_text }}
                        </p>
                    </div>
                </div>				
            </fieldset>
            <div class="submit-row">
                <input type="submit" name="_save" class="default" value="Generar Informe"/>
            </div>
        </div>
    </form>
</div>{% endblock %}

AlyMoly/reporte/templates/reporte/venta_mes.html
{% extends "admin/base_site.html" %}
{% load i18n admin_urls static admin_modify %}
{% block extrahead %}{{ block.super }}
{{ form.media }}
{% endblock %}
{% block extrastyle %}{{ block.super }}
<link rel="stylesheet" type="text/css" href="/media/admin/css/forms.css" />
{% endblock %}
{% block coltype %}{% if ordered_objects %}colMS{% else %}colM{% endif %}{% endblock %}
{% block bodyclass %}{{ opts.app_label }}-{{ opts.object_name.lower }} change-form{% endblock %}
{% block breadcrumbs %}{% if not is_popup %}
<div class="breadcrumbs">
    <a href="/admin">{% trans "Home" %}</a>
    &rsaquo; <a href="{% url 'reporte:index' %}">Reporte</a>
    &rsaquo; <a href=".">Ventas por mes</a>
</div>
{% endif %}{% endblock %}
{% block content %}<h2>Ventas por mes</h2>
<div id="content-main">
    {% block object-tools %}
    {% if change %}{% if not is_popup %}
    <ul class="object-tools">
        <li>
            <a href="history/" class="historylink">{% trans "History" %}</a>
        </li>
        {% if has_absolute_url %}
        <li>
            <a href="../../../r/{{ content_type_id }}/{{ object_id }}/" class="viewsitelink">{% trans "View on site" %}</a>
        </li>{% endif%}
    </ul>
    {% endif %}{% endif %}
    {% endblock %}
    <form id="my_form" action="." method="POST" target='_blank'>
        <div>
            <fieldset class="module aligned extrapretty">
                <h2>Ventas por mes</h2>
                <div class="description">
                    El siguiente formulario genera reportes de <strong>Ventas por mes</strong>.
                    <br/>
                    <br/>
                </div>
                <div class="form-row">
                    <div class="field-box">
                        {{ form.tipo_reporte.errors }}
                        <label class="required inline" for="id_tipo_reporte">
                            {{ form.tipo_reporte.label }}:
                        </label>
                        {{ form.tipo_reporte }}
                        <p class="help">
                            {{ form.tipo_reporte.help_text }}
                        </p>
                    </div>
                    <div class="field-box">
                        {{ form.mes.errors }}
                        <label class="required inline" for="id_mes">
                            {{ form.mes.label }}:
                        </label>
                        {{ form.mes }}
                        <p class="help">
                            {{ form.mes.help_text }}
                        </p>
                    </div>
                    <div class="field-box">
                        {{ form.anio.errors }}
                        <label class="required inline" for="id_anio">
                            {{ form.anio.label }}:
                        </label>
                        {{ form.anio }}
                        <p class="help">
                            {{ form.anio.help_text }}
                        </p>
                    </div>
                    <div class="field-box">
                        {{ form.formato.errors }}
                        <label class="required inline" for="id_formato">
                            {{ form.formato.label }}:
                        </label>
                        {{ form.formato }}
                        <p class="help">
                            {{ form.formato.help_text }}
                        </p>
                    </div>
                </div>
                <div style="display:none">
                    {{ form.tipo }}
                </div>
            </fieldset>
            <div class="submit-row">
                <input type="submit" name="_save" class="default" value="Generar Informe"/>
            </div>
        </div>
    </form>
</div>{% endblock %}