AlyMoly/inventario/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from . import views

urlpatterns = [
    url(r'^critico/$',
        views.criticos,
        name='criticos'),
    url(r'^critico/(?P<bodega>\d*)/$',
        views.criticos),
    url(r'^reiniciar/$',
        views.reiniciar,
        name='reiniciar'),
    url(r'^actual/$',
        views.actual,
        name='actual'),
    url(r'^actual/(?P<bodega>\d*)/$',
        views.actual),
    url(r'^buscar/(?P<bodega>\d*)/$',
        views.buscar),
    url(r'^existencia/actualizar/$',
        views.actualizar_existencia
        ),
    url('^$', TemplateView.as_view(
        template_name='inventario/index.html'), name="index")
]

AlyMoly/urls.py
#-*- encoding: UTF-8 -*-
from django.conf.urls import url, include
from settings import MEDIA_ROOT, DEBUG
from django.views.generic import RedirectView
from django.contrib import admin
from django.views.static import serve
admin.autodiscover()

handler500 = 'django.views.defaults.server_error'
handler404 = 'django.views.defaults.page_not_found'

urlpatterns = [
    url(r'^admin_tools/', include('admin_tools.urls')),
    url('^$', RedirectView.as_view(url='/venta/')),
    url(r'^admin/', include('AlyMoly.mantenedor.urls')),
    url(r'^admin/', include('AlyMoly.movimiento.urls')),
    url(r'^admin/reporte/', include('AlyMoly.reporte.urls', namespace='reporte')),
    url(r'^admin/inventario/', include('AlyMoly.inventario.urls', namespace='inventario')),
    url(r'^admin/utils/', include('AlyMoly.utils.urls', namespace='utils')),
    url(r'^venta/', include('AlyMoly.venta.urls', namespace='venta')),
    url(r'^devolucion/', include('AlyMoly.devolucion.urls')),
    url(r'^admin/', include(admin.site.urls)),
]

if DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {
            'document_root': MEDIA_ROOT,
        }),
    ]

AlyMoly/mantenedor/models.py
#-*- encoding: UTF-8 -*-
###############################################
# Todos los derechos reservados a:            #
# CreceLibre Consultores en Tecnologías Ltda. #
#                                             #
# ©Milton Inostroza Aguilera                  #
# minostro@minostro.com                       #
# ©Andrés Otárola Alvarado                    #
# andres@otarola.me                           #
# 2010                                        #
###############################################

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import pre_save, post_save, post_delete
from django.utils.safestring import mark_safe
from AlyMoly.mantenedor.signals import normalizar_campos
from AlyMoly.mantenedor.signals import contar_productos
from AlyMoly.mantenedor.signals import calcular_dv
from AlyMoly.mantenedor.signals import calcular_dv_trabajador
from AlyMoly.mantenedor.signals import iniciar_nuevo_inventario
from AlyMoly.mantenedor.signals import nuevo_producto_inventario

class Categoria(models.Model):
    """Representa una categoria a la que pertenece un producto"""
    nombre = models.CharField(
        max_length=200, unique=True, help_text=u'escriba el nombre de la categoría.')
    supercategoria = models.ForeignKey(
        'self', verbose_name=u"Categoría Superior", null=True, blank=True)

    def categoria_superior(self):
        if self.supercategoria:
            return mark_safe(u"""%s""" % self.supercategoria.nombre)
        else:
            return mark_safe(u"")
    categoria_superior.allow_tags = True
    categoria_superior.short_description = u'categoría superior'
    categoria_superior.admin_order_field = 'nombre'

    def __unicode__(self):
        return self.nombre.capitalize()

    class Meta:
        verbose_name = u"categoría"
        verbose_name_plural = u"categorías"
        ordering = ['nombre']


class Producto(models.Model):
    codigo_barra = models.CharField(
        max_length=100, unique=True, verbose_name=u"código de barra")
    codigo_manual = models.BooleanField(verbose_name=u"código manual")
    nombre = models.CharField(
        max_length=200, help_text='Escriba el nombre del producto.')
    marca = models.CharField(
        max_length=50, help_text='Escriba la marca del producto.')
    tipo_envase = models.CharField(max_length=50, null=True, blank=True, verbose_name=u'tipo de envase',
                                   help_text='Escriba el tipo de envase del producto, \
                                       <br />por ejemplo lata, botella, bolsa, etc.')
    capacidad = models.CharField(max_length=50, null=True, blank=True,
                                 help_text='ingrese capacidad del producto, por ejemplo 350cc ó 120gr')
    precio_costo = models.PositiveIntegerField(verbose_name=u'precio de costo',
                                               help_text=u'Ingrese el precio de costo del producto.&nbsp;&nbsp;\
                                       &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;')
    precio_venta = models.PositiveIntegerField(verbose_name=u'precio de venta',
                                               help_text=u'Ingrese el precio de venta del producto.')
    exento_iva = models.BooleanField(verbose_name=u'exento I.V.A')
    cantidad_compone = models.IntegerField(default=0, verbose_name=u'cantidad que compone',
                                           help_text='Si el producto compone a otro producto, <br />debe\
                                            indicar la cantidad que va a componer &nbsp;<br />dicho \
                                           producto, por ejemplo 6 latas de <br />cervezas componen un display.')
    compone = models.ForeignKey('self', verbose_name=u'compone a producto', null=True, blank=True,
                                help_text='Si el producto compone a otro producto, debe <br />ingresar \
                                el código de barra de ese producto,<br /> por  ejemplo si esta creando \
                                una lata de <br />cerveza, entonces debe ingresar el código de<br /> barra \
                                del display que compone.')
    subcategoria = models.ForeignKey('Categoria', verbose_name=u"Sub-Categoría",
                                     help_text=u'Seleccione la subcategoría a la cual pertenece el producto')
    stock_critico = models.PositiveIntegerField(verbose_name=u"Stock crítico")

    es_compuesto = models.BooleanField(verbose_name=u'compuesto')

    def categoria(self):
        nombre = self.subcategoria.nombre
        if self.subcategoria.supercategoria:
            nombre = self.subcategoria.supercategoria.nombre + ' / ' + nombre
        return mark_safe(u"""%s""" % nombre)
    categoria.allow_tags = True
    categoria.short_description = u'categoría'
    categoria.admin_order_field = 'subcategoria'

    def __unicode__(self):
        return "%s %s %s" % (self.nombre.capitalize(), self.tipo_envase, self.capacidad)

    def save(self, force_insert=False, force_update=False):
        super(Producto, self).save(force_insert, force_update)
        if self.es_compuesto:
            p = Producto.objects.get(codigo_barra=getattr(self,'_compuesto_por'))
            p.compone = self
            p.cantidad_compone = getattr(self,'_cantidad_compone')
            p.save()

    class Meta:
        ordering = ['nombre']


class Bodega(models.Model):
    """Representa a la bodega que contiene productos"""
    ubicacion = models.CharField(max_length=200, unique=True, verbose_name=u"ubicación",
                                 help_text=u'Describa la ubicación física de la bodega.')
    descripcion = models.TextField(null=True, blank=True, verbose_name=u"descripción",
                                   help_text=u'Escriba una descripción para conocer el propósito de la bodega.')
    venta = models.BooleanField(default=False, help_text=u'Indique si esta bodega corresponde a una \
                                                            bodega de venta.')
    productos = models.ManyToManyField(
        'Producto', through='movimiento.ProductoBodega')

    def __unicode__(self):
        return self.ubicacion.capitalize()

    def save(self, force_insert=False, force_update=False):
        """
            Al guardar una bodega se restringe que exista una única bodega del tipo
            venta para la sucursal.
        """
        if self.venta and len(Bodega.objects.exclude(id=self.id).filter(venta=True)) > 0:
            raise Exception("Usted ya cuenta con una bodega de venta")
        super(Bodega, self).save(force_insert, force_update)


class Promocion(models.Model):
    codigo = models.CharField(
        max_length=100, unique=True, verbose_name=u"código promoción")
    nombre = models.CharField(max_length=255, unique=True)
    precio_costo = models.PositiveIntegerField(verbose_name=u"precio de costo")
    precio_venta = models.PositiveIntegerField(verbose_name=u"precio de venta")
    cantidad_productos = models.IntegerField(null=True, blank=True)
    productos = models.ManyToManyField(Producto, through='ProductoPromocion')
    categoria = models.ForeignKey('Categoria', verbose_name=u"Categoría",
                                  help_text=u'Seleccione la categoría a la cual pertenece la promoción')

    def codigo_barra(self):
        return self.codigo

    def __unicode__(self):
        return u'%s' % (self.nombre)

    class Meta:
        verbose_name = u"promoción"
        verbose_name_plural = u"promociones"


class ProductoPromocion(models.Model):
    producto = models.ForeignKey('Producto')
    promocion = models.ForeignKey('Promocion')
    cantidad = models.PositiveIntegerField()

    def __unicode__(self):
        return u' '

    class Meta:
        verbose_name_plural = u"productos de promoción"
        unique_together = ('producto', 'promocion')


class Proveedor(models.Model):
    rut = models.PositiveIntegerField(u"R.U.T.", unique=True)
    dv = models.CharField(max_length=1, null=False, blank=False)
    direccion = models.CharField(max_length=200, verbose_name=u"dirección",
                                 help_text=u"Ingrese nombre de calle y número.")
    razon_social = models.CharField(max_length=100, unique=True, verbose_name=u"Razón social",
                                    help_text=u"Ingrese la razón social.")
    fono = models.CharField(max_length=200, verbose_name=u"Teléfono",
                            help_text=u"Teléfono de contacto.")
    contacto = models.CharField(max_length=200, null=True, blank=True, verbose_name=u"Nombre de contacto",
                                help_text=u"Ingrese el nombre de la persona de contacto del proveedor.")
    ingresos = models.ManyToManyField(
        'movimiento.ProductoBodega', through='movimiento.Ingreso')

    def __unicode__(self):
        return u'%s' % (self.razon_social.capitalize())

    class Meta:
        verbose_name = u"proveedor"
        verbose_name_plural = u"proveedores"


class Trabajador(models.Model):
    cedula_identidad = models.PositiveIntegerField(
        u"Cédula de identidad", unique=True)
    digito_verificador = models.CharField(max_length=1, null=False, blank=True)
    nombre = models.CharField(max_length=150)
    apellido_paterno = models.CharField(max_length=150)
    apellido_materno = models.CharField(max_length=150)
    user = models.OneToOneField(
        User, verbose_name=u'Usuario', null=True, blank=True)

    def es_activo(self):
        return self.user.is_active
    es_activo.boolean = True
    es_activo.short_description = u'Activo'

    def __unicode__(self):
        return u'%s' % (self.nombre_completo())

    def nombre_completo(self):
        return "%s %s %s" % (' '.join(nombre_.capitalize() for nombre_ in self.nombre.split(' ')),
                             self.apellido_paterno.capitalize(),
                             self.apellido_materno.capitalize())

AlyMoly/inventario/views.py
#-*- encoding: UTF-8 -*-

from django.shortcuts import render_to_response, render
from django.http import HttpResponse, HttpResponseBadRequest
from django.contrib.admin.views.decorators import staff_member_required
from django.template import RequestContext
from AlyMoly.inventario.forms import StockCriticoForm, ReiniciarInventarioForm, \
    InventarioActualForm, BuscarExistenciaForm, ActualizarExistenciaForm
from AlyMoly.movimiento.models import ProductoBodega
from AlyMoly.mantenedor.models import Producto
from AlyMoly.utils.decorators import remote_method_only
import json
from django.db.models import F, Q
from django.contrib import messages


@staff_member_required
@remote_method_only("POST")
def actualizar_existencia(request):
    """Actualiza la existencia del producto de la bodega especificada"""
    form = ActualizarExistenciaForm(request.POST)
    if form.is_valid():
        existencia = form.cleaned_data['existencia']
        producto_bodega_id = form.cleaned_data['producto_bodega']
        producto_bodega = ProductoBodega.objects.get(pk=producto_bodega_id)
        producto_bodega.existencia = existencia
        producto_bodega.save()
        return HttpResponse()
    else:
        return HttpResponseBadRequest(json.dumps(form._errors), mimetype="application/json")


@staff_member_required
def criticos(request, bodega=None):
    """Muestra todos los productos en stock crítico
    (excluyendo productos compuestos)"""
    form = StockCriticoForm()
    if bodega:
        productos = ProductoBodega.objects.filter(
            existencia__lte=F('producto__stock_critico'),
            bodega=bodega).order_by('producto__nombre').select_related()
        return render_to_response('inventario/parcial/critico.html', {
            'productos': productos.select_related(),
        })
    return render(request, 'inventario/critico.html', {'form': form, })


@staff_member_required
def buscar(request, bodega):
    """Retorna el listado de productos resultantes basado
    en el siguiente criterio:
    EXACTO: codigo de barra
    PARCIAL: nombre, marca"""
    form = BuscarExistenciaForm(request.POST)
    if request.method == 'POST' and form.is_valid():
        search = form.cleaned_data['texto']
        inner_query = Producto.objects.exclude(
            compone__exact=None
        ).values_list('compone_id', flat=True)
        existencias = ProductoBodega.objects.filter(
            bodega=bodega
        ).exclude(
            producto__in=inner_query
        ).order_by('producto__nombre')
        existencias = existencias.filter(
            Q(producto__codigo_barra__exact=search) |
            Q(producto__nombre__icontains=search) |
            Q(producto__marca__icontains=search)
        )
        return render_to_response('inventario/parcial/actual.html', {
            'existencias': existencias.select_related(),
        })


@staff_member_required
def actual(request, bodega=None):
    """ Se lista todo el inventario de la bodega seleccionada.
    Los productos compuestos son excluidos del listado."""
    form = InventarioActualForm()
    buscar_form = BuscarExistenciaForm()
    if bodega:
        id_compuestos = Producto.objects.exclude(
            compone=None).values_list('compone_id', flat=True)
        existencias = ProductoBodega.objects.filter(bodega=bodega).exclude(
            producto__in=id_compuestos).order_by('producto__nombre')
        return render(request, 'inventario/parcial/actual.html', {
            'existencias': existencias.select_related(),
        })
    return render(request,'inventario/actual.html', {
        'form': form, 'buscar_form': buscar_form,})


@staff_member_required
def reiniciar(request):
    """ Se reinicia el inventario dado un valor. Para los
    productos compuestos, se establecen existencia 0 independiente
    del valor dado."""
    if request.method == 'POST':
        form = ReiniciarInventarioForm(request.POST)
        if form.is_valid():
            bodega = form.cleaned_data['bodega']
            valor = form.cleaned_data['valor_reinicio']
            ProductoBodega.objects.filter(bodega=bodega).update(existencia=0)
            id_compuestos = Producto.objects.exclude(
                compone=None).values_list('compone_id', flat=True)
            productos = ProductoBodega.objects.filter(
                bodega=bodega).exclude(producto__pk__in=id_compuestos)
            productos.update(existencia=valor)
            messages.add_message(request, messages.INFO, 'El inventario ha sido reiniciado satisfactoriamente.')

    else:
        form = ReiniciarInventarioForm()
    return render(request, 'inventario/reiniciar.html', {'form': form})

AlyMoly/inventario/templates/inventario/actual.html
{% extends "admin/base_site.html" %}
{% load i18n admin_urls static admin_modify %}
{% block extrahead %}{{ block.super }}
{{ form.media }}
{{ buscar_form.media }}
{% endblock %}

{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="/media/admin/css/forms.css" />{% endblock %}

{% block coltype %}{% if ordered_objects %}colMS{% else %}colM{% endif %}{% endblock %}
{% block bodyclass %}{{ opts.app_label }}-{{ opts.object_name.lower }} change-form{% endblock %}
{% block breadcrumbs %}{% if not is_popup %}
<div class="breadcrumbs">
    <a href="/admin">{% trans "Home" %}</a>
    &rsaquo; <a href="/admin/inventario/">Inventario</a>
    &rsaquo; <a href=".">Inventario Actual</a>
</div>
{% endif %}{% endblock %}
{% block content %}<h2>Inventario Actual</h2>
<div id="content-main">
    {% block object-tools %}
    {% if change %}{% if not is_popup %}
    <ul class="object-tools">
        <li>
            <a href="history/" class="historylink">{% trans "History" %}</a>
        </li>
        {% if has_absolute_url %}
        <li>
            <a href="../../../r/{{ content_type_id }}/{{ object_id }}/" class="viewsitelink">{% trans "View on site" %}</a>
        </li>{% endif%}
    </ul>
    {% endif %}{% endif %}
    {% endblock %}
    <form action="." method="POST">
        <fieldset class="module aligned extrapretty">
            <h2>Inventario Actual</h2>
            <div class="description">
                En este proceso, se muestra el stock actual de productos para una <strong>bodega</strong>
                seleccionada. Es posible tambi&eacute;n, establecer un valor arbitrario de existencia para un producto dado. Si se desea
				establecer un valor de existencia, debe estar seguro de que el valor que ingresar&aacute; es el valor correcto.
                <br/>
                <br/>
            </div>
            <div class="form-row nombre marca  ">
                <div class="field-box">
                    {{ form.bodega.errors }}
                    <label class="required inline" for="id_marca">
                        {{ form.bodega.label }}:
                    </label>
                    {{ form.bodega }}
                    <p class="help">
                        {{ form.bodega.help_text }}
                    </p>
                </div>
            </div>
            <br/>
        </fieldset>
    </form>
    <style type="text/css">
        #changelist-search {
            background: #E1E1E1 url(/media/img/nav-bg.gif) repeat-x scroll left top;
            border-bottom: 1px solid #DDDDDD;
            color: #666666;
            padding: 3px;
        } .qs_input {
            width: 300px
        }
    </style>
    <div id="changelist" class="module filtered">
        <form class="quicksearch" id="changelist-search" action="#">
            <label class="qs_label">
                <img src="/media/img/icon_searchbox.png" alt="Search"/>
            </label>{{buscar_form.texto}}<span class="loader" id="loader" style="display: none;"><img src="/media/img/ajax-loader.gif" alt="Search"/></span>
        </form>
        <div id="inventario-actual">
        </div>
    </div>
</div>{% endblock %}

AlyMoly/inventario/templates/inventario/critico.html
{% extends "admin/base_site.html" %}
{% load i18n admin_modify admin_static %}
{% load admin_urls %}
{% block extrahead %}{{ block.super }}
{{ form.media }}
{% endblock %}
{% block extrastyle %}{{ block.super }}
<link rel="stylesheet" type="text/css" href="/media/admin/css/forms.css" />
{% endblock %}
{% block coltype %}{% if ordered_objects %}colMS{% else %}colM{% endif %}{% endblock %}
{% block bodyclass %}{{ opts.app_label }}-{{ opts.object_name.lower }} change-form{% endblock %}
{% block breadcrumbs %}{% if not is_popup %}
<div class="breadcrumbs">
    <a href="/admin">{% trans "Home" %}</a>
    &rsaquo; <a href="/admin/inventario/">Inventario</a>
    &rsaquo; <a href=".">Stock Cr&iacute;tico</a>
</div>
{% endif %}{% endblock %}
{% block content %}<h2>Stock Cr&iacute;tico</h2>
<div id="content-main">
    {% block object-tools %}
    {% if change %}{% if not is_popup %}
    <ul class="object-tools">
        <li>
            <a href="history/" class="historylink">{% trans "History" %}</a>
        </li>
        {% if has_absolute_url %}
        <li>
            <a href="../../../r/{{ content_type_id }}/{{ object_id }}/" class="viewsitelink">{% trans "View on site" %}</a>
        </li>{% endif%}
    </ul>
    {% endif %}{% endif %}
    {% endblock %}
    <form id="my_form" action="." method="POST">
        <div>
            <fieldset class="module aligned extrapretty">
                <h2>Stock Cr&iacute;tico</h2>
                <div class="description">
                    El siguiente listado muestra todos los productos que se encuentren bajo <strong>stock cr&iacute;tico</strong>.
                    <br/>
                    <br/>
                </div>
                <div class="form-row nombre marca  ">
                    <div class="field-box">
                        {{ form.bodega.errors }}
                        <label class="required inline" for="id_proveedor">
                            {{ form.bodega.label }}:
                        </label>
                        {{ form.bodega }}
                        <p class="help">
                            {{ form.bodega.help_text }}
                        </p>
                    </div>
                </div>
                <div style="display:none">
                    {{ form.tipo }}
                </div>
            </fieldset>
        </div>
    </form>
    <style type="text/css">
        #changelist-search {
            background: #E1E1E1 url(/media/img/nav-bg.gif) repeat-x scroll left top;
            border-bottom: 1px solid #DDDDDD;
            color: #666666;
            padding: 3px;
        } .qs_input {
            width: 300px
        }
    </style>

    <div id="stock-critico">
    </div>

</div>{% endblock %}

AlyMoly/inventario/templates/inventario/index.html
{% extends "admin/base_site.html" %}
{% load i18n %}

{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="/media/admin_tools/css/dashboard.css" />{% endblock %}

{% block coltype %}colMS{% endblock %}

{% block bodyclass %}dashboard{% endblock %}
{% block breadcrumbs %}
<div class="breadcrumbs">
    <a href="/admin">{% trans "Home" %}</a>
    &rsaquo; <a href="../../">Movimiento</a>
</div>{% endblock %}
{% block content %}
<div id="content-main">
      <div class="module">
        <table>
            <caption>
                <a href="{% url 'inventario:index' %}" class="section">Inventario</a>
            </caption>
            <tr>
                <th scope="row">
                    <a href="{% url 'inventario:actual' %}">Inventario actual</a>
                </th>
                <td>
                    &nbsp;
                </td>
                <td>
                    &nbsp;
                </td>
            </tr>
            <tr>
                <th scope="row">
                    <a href="{% url 'inventario:reiniciar' %}">Reiniciar Inventario</a>
                </th>
                <td>
                    &nbsp;
                </td>
                <td>
                    &nbsp;
                </td>
            </tr>
            <tr>
                <th scope="row">
                    <a href="{% url 'inventario:criticos' %}">Stock Cr&iacute;tico</a>
                </th>
                <td>
                    &nbsp;
                </td>
                <td>
                    &nbsp;
                </td>
            </tr>
        </table>
    </div>
</div>
{% endblock %}
{% block sidebar %}
<div id="content-related">
    <div class="module" id="recent-actions-module">
        <h2>{% trans 'Recent Actions' %}</h2>
        <h3>{% trans 'My Actions' %}</h3>
        {% load log %}
        {% get_admin_log 10 as admin_log for_user user %}
        {% if not admin_log %}
        <p>
            {% trans 'None available' %}
        </p>
        {% else %}
        <ul class="actionlist">
            {% for entry in admin_log %}
            <li class="{% if entry.is_addition %}addlink{% endif %}{% if entry.is_change %}changelink{% endif %}{% if entry.is_deletion %}deletelink{% endif %}">
                {% if not entry.is_deletion %}<a href="{{ entry.get_admin_url }}">{% endif %}{{ entry.object_repr }}{% if not entry.is_deletion %}</a>{% endif %}
                <br/>
                <span class="mini quiet">{% filter capfirst %}{% trans entry.content_type.name %}{% endfilter %}</span>
            </li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
</div>
{% endblock %}

AlyMoly/inventario/templates/inventario/reiniciar.html
{% extends "admin/base_site.html" %}
{% load i18n admin_modify admin_static %}
{% load admin_urls %}
{% block extrahead %}{{ block.super }}
{{ form.media }}
{% endblock %}
{% block extrastyle %}{{ block.super }}
<link rel="stylesheet" type="text/css" href="/media/admin/css/forms.css" />
{% endblock %}
{% block coltype %}{% if ordered_objects %}colMS{% else %}colM{% endif %}{% endblock %}
{% block bodyclass %}{{ opts.app_label }}-{{ opts.object_name.lower }} change-form{% endblock %}
{% block breadcrumbs %}{% if not is_popup %}
<div class="breadcrumbs">
    <a href="/admin">{% trans "Home" %}</a>
    &rsaquo; <a href="/admin/inventario/">inventario</a>
    &rsaquo; <a href=".">Reiniciar Inventario</a>
</div>
{% endif %}{% endblock %}
{% block content %}<h2>Reiniciar Inventario</h2>
<div id="content-main">
    {% block object-tools %}
    {% if change %}{% if not is_popup %}
    <ul class="object-tools">
        <li>
            <a href="history/" class="historylink">{% trans "History" %}</a>
        </li>
        {% if has_absolute_url %}
        <li>
            <a href="../../../r/{{ content_type_id }}/{{ object_id }}/" class="viewsitelink">{% trans "View on site" %}</a>
        </li>{% endif%}
    </ul>
    {% endif %}{% endif %}
    {% endblock %}
    <form id="my_form" action="." method="POST">
        <div>
            <fieldset class="module aligned extrapretty">
                <h2>Reiniciar Inventario</h2>
                <div class="description">
                   El siguiente formulario permite reiniciar el inventario de la bodega seleccionada para un valor &uacute;nico.
                    <br/>
                    <br/>
                </div>
                <div class="form-row nombre marca  ">
                    <div class="field-box">
                        {{ form.bodega.errors }}
                        <label class="required inline" for="id_proveedor">
                            {{ form.bodega.label }}:
                        </label>
                        {{ form.bodega }}
                        <p class="help">
                            {{ form.bodega.help_text }}
                        </p>
                    </div>
                </div>
				                <div class="form-row nombre marca  ">
                    <div class="field-box">
                        {{ form.valor_reinicio.errors }}
                        <label class="required inline" for="id_proveedor">
                            {{ form.valor_reinicio.label }}:
                        </label>
                        {{ form.valor_reinicio }}
                        <p class="help">
                            {{ form.valor_reinicio.help_text }}
                        </p>
                    </div>

                </div>
                <div style="display:none">
                    {{ form.tipo }}
                </div>
            </fieldset>
            <div class="submit-row">
                <input type="submit" name="_save" class="default" value="Reiniciar"/>
            </div>
        </div>
    </form>
</div>{% endblock %}